# Generated by Django 5.2.8 on 2025-11-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
