# Generated by Django 5.2.8 on 2025-11-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_period_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='cycle_length',
        ),
        migrations.RemoveField(
            model_name='period',
            name='next_period',
        ),
        migrations.AddField(
            model_name='period',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='end_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='period',
            name='mood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
